name: mfvidip
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  # - _openmp_mutex=4.5
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  # - ld_impl_linux-64=2.35.1
  - libffi=3.3
  # - libgcc-ng=9.3.0
  # - libgomp=9.3.0
  # - libstdcxx-ng=9.3.0
  - ncurses=6.2
  - openssl=1.1.1k
  - pip=21.1.3
  - python=3.9.5
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.36.0
  - tk=8.6.10
  - tzdata=2021a
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - cycler==0.10.0
    - decorator==4.4.2
    - gpytorch==1.5.0
    - imageio==2.9.0
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - matplotlib==3.4.2
    - networkx==2.5.1
    - numpy==1.21.0
    - pandas==1.3.0
    - pillow==8.3.1
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pytz==2021.1
    - pywavelets==1.1.1
    - scikit-image==0.18.2
    - scikit-learn==0.24.2
    - scipy==1.7.0
    - seaborn==0.11.1
    - six==1.16.0
    - threadpoolctl==2.2.0
    - tifffile==2021.7.2
    - torch==1.9.0
    - torchvision==0.10.0
    - tqdm==4.61.2
    - typing-extensions==3.10.0.0
# prefix: /home/malte/anaconda3/envs/mfvidip
